// Generated by CoffeeScript 1.6.3
(function() {
  window.Request = function() {
    this.get = function(data, successCallback) {
      $.ajax({
        url: 'protected/ajax.php',
        type: 'post',
        data: data,
        dataType: 'json',
        success: function(data) {
          return typeof successCallback === "function" ? successCallback(data) : void 0;
        },
        error: function(e, type, message) {
          console.error(message);
          return graphic.message('Error', message);
        }
      });
    };
  };

}).call(this);
