// Generated by CoffeeScript 1.6.3
(function() {
  var Game;

  Game = function(lang) {
    this.mainword = '';
    this.timer = 0;
    this.score = 0;
    this.lettersWeights = null;
    this.correctAnswers = [];
    this.level = 1;
    this.achievScore = 0;
    this.maxAchievScore = 0;
    this.rareLetters = [];
    this.maxLevel = 50;
    this.userId = 0;
    this.userName = '';
    this.isFirst = false;
    this.lang = lang;
    this.used = {
      rareLetters: 0,
      shortWords: 0,
      longWords: 0,
      palindrome: 0,
      anagram: 0,
      expensiveWords: 0
    };
    this.isNewGame = function() {
      var strGameState;
      strGameState = localStorage.getItem('wordGame');
      return strGameState === null || strGameState === "" || strGameState === 'null';
    };
    this.play = function() {
      if (this.isNewGame()) {
        return this.getLanguage('completeSetup');
      } else {
        return this.load();
      }
    };
    return this.getLanguage = function(callback) {
      var _this = this;
      return $.getScript("js/game.language." + this.lang + ".js", function() {
        return _this.callback();
      });
    };
  };

}).call(this);
