// Generated by CoffeeScript 1.6.3
(function() {
  require(["lib/jquery-2.0.2.min", "lib/jquery-ui.min", "lib/jquery.jgrowl.min", "bootstrap/js/bootstrap.js", "game.functions"]);

  require(["lib/coffee-script"], function(CoffeeScript) {
    return $(function() {
      var loadCoffee;
      loadCoffee = function(files) {
        var $head, file, load, _i, _len, _results;
        $head = $("head");
        load = function(file) {
          var coffeeFile;
          coffeeFile = "coffee/" + file + ".coffee";
          return $.get(coffeeFile, function(content) {
            var compiled;
            compiled = CoffeeScript.compile(content, {
              bare: true
            });
            return $("<script />").attr("type", "text/javascript").html(compiled).appendTo($head);
          });
        };
        _results = [];
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          _results.push(load(file));
        }
        return _results;
      };
      loadCoffee(['game', 'game.request', 'game.graphic', 'game.ready']);
    });
  });

}).call(this);
