// Generated by CoffeeScript 1.6.3
(function() {
  require(["lib/jquery-2.0.2.min", "lib/jquery-ui.min", "lib/jquery.jgrowl.min", "bootstrap/js/bootstrap.js", "game.functions", 'game', 'game.request', 'game.graphic', 'game.ready']);

}).call(this);
